version: '3.7'
services:
  rabbit:
    image: rabbitmq:3.7.14-management
    environment: 
      RABBITMQ_DEFAULT_USER: secure
      RABBITMQ_DEFAULT_PASS: secure
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    container_name: rabbit